/*
@NAME: Hannah Robinow
@DATE: 5 April 2018
@DESCRIPTION: Use four functions to reverse an array generated by user input.
*/

#include <iostream>
#include <cmath>
#include <fstream>
#include <iomanip>
using namespace::std;

//function headers.
void inputData(istream &, int[], int);
void printData(ostream &, const int[], int);
void copyArray(const int orig[], int dup[], int);
void revCopy(const int orig[], int rev[], int);

void main() {
	int size = 0;
	int original[60];


	cout << "Enter array elements: " << endl;
	for (int i = 0; i < size; i++) {
		cout << "Enter array # " << i << " element: " << endl;
		cin >> original[size];
	}

	cout << "Data stored in array!" << endl;




}


//input an array.
void inputData(istream &, int original[], int a) {
	for (int i = 0; i < a; i++) {
		cin >> original[i];
	}
}

//display the array.
void printData(ostream &, int original[], int b) {
	for (int i = 0; i < b; i++) {
		cout << original[i] << endl;
	}
}

//make a copy of the array.
void copyArray(int original[], int dup[], int a) {
	for (int i = 0; i < a; i++) {
		dup[i] = original[i];
	}
}

void revCopy(int original[], int rev[], int size) {
	int temp;
	size--;
	for (int i = 0; size >= i; i++) {
		temp = original[i];
		original[i] = rev[size];
		rev[size] = temp;
	}
}
